### PR TITLE
strip more, simplify code, assembly hack, 5328 bytes

### PR DESCRIPTION
**Pull request by tleydxdy**

### CODE REVIEW

**Comment by Francesco149** [comment]
very clever way to construct the syscall number, nice

**Comment by Francesco149** [comment]
.bss strip won't work due to http_buf being in it, but i guess I could move it to the stack in the future

**Comment by tleydxdy** [comment]
it worked on both of my machines, (intel and amd)

**Comment by Francesco149** [comment]
it gives EFAULT with a bigger file for me. `test.html` works fine though. maybe if we make http_buf smaller

**Comment by tleydxdy** [comment]
I can even serve the whole emacs manual (3.7M) from it. hmm

**Comment by tleydxdy** [comment]
yeah, I removed all the static variables, and now the binary is 1208 bytes long...... wtf

**Pull request merged**
